<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="47125" started-at="2020-08-19T04:06:09Z" finished-at="2020-08-19T04:06:56Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="47125" started-at="2020-08-19T04:06:09Z" finished-at="2020-08-19T04:06:56Z">
      <class name="GitTest.GitTest">
        <test-method status="FAIL" signature="login()[pri:0, instance:GitTest.GitTest@2ff4f00f]" name="login" duration-ms="46803" started-at="2020-08-19T09:36:09Z" finished-at="2020-08-19T09:36:56Z">
          <exception class="java.io.IOException">
            <message>
              <![CDATA[Destination 'C:\Users\eshra\workspace\A14_GitTest_Sample\screen' exists but is a directory]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.io.IOException: Destination 'C:\Users\eshra\workspace\A14_GitTest_Sample\screen' exists but is a directory
	at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1130)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1091)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
	at GitTest.GitTest.login(GitTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
            </full-stacktrace>
          </exception> <!-- java.io.IOException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
      </class> <!-- GitTest.GitTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
